### ISSUE TITLE
Could you share the mean emb?

### ISSUE THREAD

**Issue by betterze** [yuhui-zh15/drml#2]
Dear Yuhui,

Thank you for your great work. It is very interesting. 

In section 2.1, you mention that the modality gap could be closed by subtracting the mean, x-E[X] and y-E[Y]. Could you share the mean image emb E[X]  and text emb E[Y] with me? Which version of the CLIP model you are using? 

Thank you for your help.

Best Wishes,

Zongze

**Comment by yuhui-zh15** [comment]
Dear Zongze,

Thanks for your interest in our work. E[X] and E[Y] can be simply computed on any dataset using any model. We use COCO image captions and CLIP-ViT-B/32 to compute. Unfortunately, we don't have the cached files to share but the process should be rather simple.

**Comment by betterze** [comment]
Thank you for your reply. I really appreciate it.
